name: ProjectG7
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - matplotlib
  - dvc
  - ipywidgets
  - scikit-learn=1.8.0
  - jupyter
  - pandas=2.2.2
  - seaborn
  - imbalanced-learn=0.14.1
  - joblib=1.4.2
  - xgboost=3.2.0
  - lightgbm=4.6.0
  - optuna
  - streamlit=1.37.1
  - shap=0.46.0
  - plotly=5.24.1
