name: ProjectG7
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - pydantic
  - numpy
  - matplotlib
  - dvc
  - ipywidgets
  - scikit-learn
  - jupyter
  - pandas
  - seaborn
  - imbalanced-learn
  - joblib
  - feature-engine
  - xgboost
  - lightgbm
  - optuna
  - streamlit
  - shap

  - plotly
